# Generated by Django 4.2.10 on 2024-02-24 18:58

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pizza.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', pizza.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CardExpiry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.DecimalField(decimal_places=2, default=7, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pepperoni', models.BooleanField(default=False, verbose_name='Pepperoni')),
                ('chicken', models.BooleanField(default=False, verbose_name='Chicken')),
                ('ham', models.BooleanField(default=False, verbose_name='Ham')),
                ('pineapple', models.BooleanField(default=False, verbose_name='Pineapple')),
                ('peppers', models.BooleanField(default=False, verbose_name='Peppers')),
                ('mushrooms', models.BooleanField(default=False, verbose_name='Mushrooms')),
                ('onions', models.BooleanField(default=False, verbose_name='Onions')),
                ('crust', models.CharField(choices=[('REGULAR', 'Regular'), ('THIN', 'Thin')], default='REGULAR', max_length=50)),
                ('cheese', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza.cheese')),
                ('sauce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza.sauce')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza.size')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(default='Dublin', max_length=150)),
                ('card_number', models.PositiveBigIntegerField(default=0, validators=[pizza.models.validate_length])),
                ('cvv', models.IntegerField(default=0, validators=[pizza.models.validate_cvv])),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('expiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.cardexpiry')),
                ('pizza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza.pizza')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
